### PR TITLE
netstandard1.5 and netcore1.1 builds.

### PR DESCRIPTION
**Pull request by killwort**
I've added project files to build this library for .NETCore 1.2 and .NETStandard 1.5. While porting I've dropped support for Privacy* classes except for 3DES (AES implementation has slightly different parameters in newer framework, I'm not sure if it would work well and I don't have SNMP server with security to test it; DES is really obsolete and insecure).

Project is prepared for publication on nuget, just run `dotnet pack SnmpSharpNet-Std.sln` and it will generate package for publishing.

### CODE REVIEW

**Comment by timematcher** [comment]
How can we see this commit in nuget @rqx110  @killwort  ? Thanks for your great work so far!

**Comment by killwort** [comment]
I haven't pushed this package to nuget, just added buld-time support for it.

**Comment by timematcher** [comment]
Please keep support for .NET 2.0/4.0 because several agents user windows XP 64 bit and a .NET CORE-only library will not work as .NET 4.0 is highest .NET framework supported on Windows XP 64 and 32 bit OSes. Despite my dislike for Windows XP, we are forced to support these Platforms.

**Comment by lextm** [comment]
@timematcher Windows XP is long dead, so when you are "forced to support" it, it is not reasonable to drag others back.

**Comment by lextm** [comment]
Generally speaking you should keep DES, even if you mark it as obsolete. Many devices out there might only support DES, and the risks of running DES inside a corporate environment (which is almost true for all SNMP scenarios) is relatively low.

AES CFB mode is not supported on .NET Core. You can find more information from https://github.com/dotnet/corefx/issues/4647

**Pull request closed without merging**
